// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeEjEULqhjMPvr8NOEx8_KMxkRiecIzwM',
    appId: '1:868318242363:android:f935c226855ae201241e1e',
    messagingSenderId: '868318242363',
    projectId: 'menta-ray',
    databaseURL: 'https://menta-ray-default-rtdb.firebaseio.com',
    storageBucket: 'menta-ray.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD89vApCqluSKrEq_nafVOmdFO-_94GA_E',
    appId: '1:868318242363:web:f6724be4ec136ad4241e1e',
    messagingSenderId: '868318242363',
    projectId: 'menta-ray',
    authDomain: 'menta-ray.firebaseapp.com',
    databaseURL: 'https://menta-ray-default-rtdb.firebaseio.com',
    storageBucket: 'menta-ray.firebasestorage.app',
    measurementId: 'G-4CD45KCZVC',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD89vApCqluSKrEq_nafVOmdFO-_94GA_E',
    appId: '1:868318242363:web:f6724be4ec136ad4241e1e',
    messagingSenderId: '868318242363',
    projectId: 'menta-ray',
    authDomain: 'menta-ray.firebaseapp.com',
    databaseURL: 'https://menta-ray-default-rtdb.firebaseio.com',
    storageBucket: 'menta-ray.firebasestorage.app',
    measurementId: 'G-4CD45KCZVC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_xoDGOU-aNGdZPAI7Rjdx1FFACH8JAaA',
    appId: '1:868318242363:ios:0dfd1c53e12ce15e241e1e',
    messagingSenderId: '868318242363',
    projectId: 'menta-ray',
    databaseURL: 'https://menta-ray-default-rtdb.firebaseio.com',
    storageBucket: 'menta-ray.firebasestorage.app',
    iosBundleId: 'com.example.cuteMessaging',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_xoDGOU-aNGdZPAI7Rjdx1FFACH8JAaA',
    appId: '1:868318242363:ios:0dfd1c53e12ce15e241e1e',
    messagingSenderId: '868318242363',
    projectId: 'menta-ray',
    databaseURL: 'https://menta-ray-default-rtdb.firebaseio.com',
    storageBucket: 'menta-ray.firebasestorage.app',
    iosBundleId: 'com.example.cuteMessaging',
  );
}
