// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLrU3KAxVarkkpGUCmCkhT97yBnBLfOVc',
    appId: '1:938809862686:web:ab957bd310e9ad24f5dc0f',
    messagingSenderId: '938809862686',
    projectId: 'messaging-c7c45',
    authDomain: 'messaging-c7c45.firebaseapp.com',
    storageBucket: 'messaging-c7c45.firebasestorage.app',
    measurementId: 'G-MRFVSVF0M9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbc99X_uOqwLhBp_T0SQ9HLguDV7jGiKo',
    appId: '1:938809862686:android:ffb7f188e1936226f5dc0f',
    messagingSenderId: '938809862686',
    projectId: 'messaging-c7c45',
    storageBucket: 'messaging-c7c45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvPN7sd4ypilo-NXn1illQrdMM_FvCY2Q',
    appId: '1:938809862686:ios:ca3c04fdf28ae92df5dc0f',
    messagingSenderId: '938809862686',
    projectId: 'messaging-c7c45',
    storageBucket: 'messaging-c7c45.firebasestorage.app',
    iosBundleId: 'com.example.cuteMessaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvPN7sd4ypilo-NXn1illQrdMM_FvCY2Q',
    appId: '1:938809862686:ios:ca3c04fdf28ae92df5dc0f',
    messagingSenderId: '938809862686',
    projectId: 'messaging-c7c45',
    storageBucket: 'messaging-c7c45.firebasestorage.app',
    iosBundleId: 'com.example.cuteMessaging',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLrU3KAxVarkkpGUCmCkhT97yBnBLfOVc',
    appId: '1:938809862686:web:84ade37b7afbbb34f5dc0f',
    messagingSenderId: '938809862686',
    projectId: 'messaging-c7c45',
    authDomain: 'messaging-c7c45.firebaseapp.com',
    storageBucket: 'messaging-c7c45.firebasestorage.app',
    measurementId: 'G-5C7HCRPFHL',
  );
}
